### ISSUE TITLE
additional steps

### ISSUE THREAD

**Issue by AlJohri** [WPMedia/laptop#1]
- install cisco vpn
- set up git https credential keychain

from https://github.com/MikeMcQuaid/strap/blob/54d55c5cd80647b4a5581514283d1c622ebda55d/bin/strap.sh#L255-L270

```bash
# Setup GitHub HTTPS credentials.
if git credential-osxkeychain 2>&1 | grep $Q "git.credential-osxkeychain"
then
  if [ "$(git config --global credential.helper)" != "osxkeychain" ]
  then
    git config --global credential.helper osxkeychain
  fi

  if [ -n "$STRAP_GITHUB_USER" ] && [ -n "$STRAP_GITHUB_TOKEN" ]
  then
    printf "protocol=https\\nhost=github.com\\n" | git credential-osxkeychain erase
    printf "protocol=https\\nhost=github.com\\nusername=%s\\npassword=%s\\n" \
          "$STRAP_GITHUB_USER" "$STRAP_GITHUB_TOKEN" \
          | git credential-osxkeychain store
  fi
fi
```

- install homebrew-perso-tool
    - yarn conflicts with apache-spark
- install vscode extensions

```bash
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension samuelcolvin.jinjahtml
code --install-extension mohsen1.prettify-json
code --install-extension esbenp.prettier-vscode
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension redhat.vscode-yaml
code --install-extension grapecity.gc-excelviewer
code --install-extension james-yu.latex-workshop
code --install-extension josephtbradley.hive-sql
code --install-extension lextudio.restructuredtext
code --install-extension mikestead.dotenv
code --install-extension nobuhito.printcode
code --install-extension octref.vetur
code --install-extension rebornix.ruby
```

- set up ssh key add to github.com
- set git config name and email
- set up ~/.ssh/config file
- download pem files

**Comment by Greymalkin** [comment]
Might I suggest adding an installation for VirtualEnv Wrapper?

**Comment by AlJohri** [comment]
hi @Greymalkin! thanks for your interest. I originally made this repo for our personalization team at the post- our team currently uses [pipenv](https://github.com/pypa/pipenv) for managing python dependencies and virtualenvs (although this may change in the near future as pipenv is unmaintained).

to be honest, I personally find virtualenvwrapper fairly difficult to manage when trying to do automate setting up a local development environment and fairly brittle since it's a collection of shell scripts. for example, if I wanted to have a `make local-install` command in my project's Makefile that creates a virtualenv and installs the python dependencies its neigh impossible with virtualenvwrapper. you have to resort to creating READMEs with all the ritualistic steps: `mkvirtualenv blah`, `workon blah`, `pip install -r requirements.txt`, etc. etc. it also sources things in the current shell instead of creating a subshell which I find generally creates issues.

the default python3 `venv`, `pipenv`, and `poetry` have all worked a bit better for me compared to `virtualenvwrapper`.

for example, a project's `make local-install` command can be defined as follows:

#### python3's default venv
```
local-install:
    python3 -m venv .venv
    .venv/bin/pip install -r requirements.txt
```

#### pipenv

```
local-install:
    PIPENV_VENV_IN_PROJECT=1 pipenv install
```

#### poetry

```
local-install:
    poetry install
```

Unfortuantely pipenv isn't well-maintained as of late, so I/we may switch over to [poetry](https://github.com/sdispater/poetry) or default python venv in the near future.

**Comment by Greymalkin** [comment]
Yeah, I'm also at the post.  We use both pipenv and virtualenvwrapper with various adapters, so it would be super helpful to have both in the script.  I'm setting up a temporary laptop today and someone pointed me to the script.  It was super helpful but... still need to get virtualenvwrapper installed.
